CREATE TABLE GK_USER(
    ID VARCHAR(36) NOT NULL,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255),
    ROLES VARCHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE CUSTOMER(
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (ID) REFERENCES GK_USER(ID)
);

CREATE TABLE CUSTOMER_ADDRESS(
    CS_ID VARCHAR(36) NOT NULL,
    POSTAL_CODE VARCHAR(15) NOT NULL,
    ADDRESS_NUMBER INTEGER,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PRIMARY KEY(CS_ID, POSTAL_CODE)
);

CREATE TABLE ADDRESS(
    POSTAL_CODE VARCHAR(15) UNIQUE NOT NULL,
    STREET_NAME VARCHAR(100),
    DISTRICT VARCHAR(100),
    CITY_ID VARCHAR(36),
    PRIMARY KEY(POSTAL_CODE)
);

CREATE TABLE CITY(
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    STATE_NAME VARCHAR(255) NOT NULL,
    STATE_ABBREVIATION VARCHAR(2) NOT NULL,
    PRIMARY KEY(ID)
)